language: go
go:
  - 1.8.x

env:
  global:
  - PATH=$GOROOT/bin:$PATH
  - GO15VENDOREXPERIMENT=1

before_install:
  - go get github.com/modocache/gover
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
script:
  - bash -x hack/test.sh
